### ISSUE TITLE
Unable to set preferences

### ISSUE THREAD

**Issue by fsamareanu** [ratanakvlun/deluge-ltconfig#18]
Hello,

I'm running ubuntu 18.04 with deluge 2.0.3-2 from ppa. When setting preferences to high performance seed I get this in the console:

21:15:05.163 [ERROR   ][deluge.ui.web.json_api     :185 ] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: Expecting property name enclosed in double quotes: line 53 column 6 (char 1665)
Traceback (most recent call last):
  File "/home/owner/.local/usr/local/lib/python3.6/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/home/owner/.config/deluge/plugins/ltConfig-2.0.0-py3.6.egg/ltconfig/core.py", line 196, in set_preferences
    self._config.save()
  File "/home/owner/.local/usr/local/lib/python3.6/dist-packages/deluge/config.py", line 468, in save
    loaded_data = json.loads(data[start:end])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 53 column 6 (char 1665)

]

**Comment by barendlab** [comment]
Hi Ok you can try 

sudo apt-get remove --purge deluge

Then follow dis and make sure you ar in root 
And give root Privileges

usermod -aG sudo username 

sudo apt-get install deluge-webui deluged

sudo nano /etc/systemd/system/deluged.service

[Unit]
Description=Deluge Bittorrent Client Daemon
After=network-online.target

[Service]
Type=simple
User=Username 
Group=Username 
UMask=007

ExecStart=/usr/bin/deluged -d

Restart=on-failure

# Configures the time to wait before service is stopped forcefully.
TimeoutStopSec=300

[Install]
WantedBy=multi-user.target
systemctl start deluged
systemctl enable deluged

sudo nano /etc/systemd/system/deluge-web.service

[Unit]
Description=Deluge Bittorrent Client Web Interface
After=network-online.target

[Service]
Type=simple

User=Username
Group=Username 
UMask=027

ExecStart=/usr/bin/deluge-web

Restart=on-failure

[Install]
WantedBy=multi-user.target

systemctl start deluge-web
